---
name: snyk

on:
  push:
    branches:
      - 'master'     # matches every branch
  pull_request:
    branches:
      - master

jobs:
  security:
    runs-on: 
      - master
    name: snyk
    steps:
       - name: checkout
         uses: actions/checkout@v2
       - name: Vulnerability scan
         uses: snyk/actions/iac@master
         env:
           SNYK_TOKEN: ${{ secrets.ARC_SNYK_TOKEN }}
         with:
           command: monitor
           args: --severity-threshold=low
       - name: Set up Node 14
         uses: actions/setup-node@v3
         with:
             node-version: 14
       - name: install Snyk CLI
         run: npm install -g snyk
       - name: snyk monitor
         run: snyk iac test   


  
